# Generated by Django 3.2.4 on 2022-01-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(default=123, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
