# Generated by Django 4.0 on 2022-01-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_postmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='thumbnail',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
    ]
