# Generated by Django 4.0 on 2022-01-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_workmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='github_url',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='cost',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='duration',
            field=models.CharField(max_length=200),
        ),
    ]
