# Generated by Django 3.2.4 on 2022-01-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_workmodel_github_url_alter_workmodel_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='status',
            field=models.CharField(choices=[('p', 'published'), ('d', 'draft')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
