# Generated by Django 4.0 on 2022-01-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_postmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='status',
            field=models.CharField(choices=[('p', 'published'), ('d', 'draft')], default='d', max_length=1),
        ),
    ]
