# Generated by Django 4.0 on 2022-02-15 13:55

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_postmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=18, max_length=18, unique=True),
        ),
    ]
